config/routes.rb
Tfc::Application.routes.draw do
  resource :survey, :only => [:new, :create]

  resources :reports, :only => [:index] do
    get :summary, :on => :collection
  end

  offline = Rack::Offline.configure do
    cache "assets/application-fb983cc3f25c662a1451ed8644ca02eb.js"
    cache "assets/application-48bd90fce6838f1fa2aeab5dcce6d26c.css"
    cache "on_the_road.png"
    cache "404.html"
    cache "500.html"
    network "/"
  end
  match "/survey_cache.manifest" => offline

end

app/models/mixins/searchable.rb
module Mixins
  module Searchable

    def self.included(base)
      base.extend ClassMethods
    end

    module ClassMethods

      def make_searchable(opts={})
        cattr_accessor :search_fields
        cattr_accessor :search_includes
        self.search_fields = opts.delete(:fields)
        self.search_includes = opts.delete(:include)
        # need to account for joins (removed it now due to Arel syntax)
        scope :with_keywords, lambda { |query|
          chain = nil
          if self.search_includes && self.search_includes.size > 0 # always expect array
            self.search_includes.each {|j| chain = chain ? chain.includes(j.to_sym) : includes(j.to_sym) }
          end
          chain ? chain.where(build_search_conditions(query)) : where(build_search_conditions(query))
        }
      end

      def build_search_conditions(query)
        words = query.strip.upcase.split.collect{|w| w.strip }
        query = []
        params = {}
        words.each_with_index do |word, i|
          key = "word#{i}"
          query << build_query_string_for_key(key)
          params[key.to_sym] = "%#{word}%"
        end
        query = query.join(" AND ")
        [query, params]
      end

      # This will build something like "(UPPER(videos.name) LIKE :#{key} OR UPPER(videos.description) LIKE :#{key} OR UPPER(videos.tags) LIKE :#{key})"
      def build_query_string_for_key(key)
        "(" + self.search_fields.collect {|field| "UPPER(CAST(#{field.to_s} AS varchar)) LIKE :#{key}"  }.join(" OR ") + ")"
      end
    end
  end
end

app/models/request_log.rb
class RequestLog < ActiveRecord::Base
  
end

app/models/survey.rb
class Survey < ActiveRecord::Base
  make_searchable :fields => %w{surveys.first_name surveys.last_name surveys.email surveys.postal_code surveys.phone_number}

  def day_entered
    self.entered_at.strftime('%b %e, %Y')
  end

  def time_entered
    self.entered_at.strftime('%l:%H%P')
  end

  scope :daily_summaries, lambda{ |start_date, end_date|
    start_date ||= Survey.order('entered_at ASC').first.entered_at
    end_date ||= Survey.order('entered_at DESC').first.entered_at

    where(:entered_at => (start_date..end_date)).
      group("DATE_TRUNC('day', entered_at)").
      select(
      "DATE_TRUNC('day', entered_at) as entered_date,
        MIN(entered_at - date_trunc('day', entered_at)) as start_time,
        MAX(entered_at - date_trunc('day', entered_at)) as end_time,
        COUNT(*) as num_of_entrees,
        SUM(CASE tfc_opt_in WHEN TRUE THEN 1 ELSE 0 END) as num_of_tfc_opt_ins,
        SUM(CASE rogers_opt_in WHEN TRUE THEN 1 ELSE 0 END) as num_of_rogers_opt_ins
      "
    ).order("DATE_TRUNC('day', entered_at) ASC")
  }

  scope :order_by_date_entered, order('entered_at ASC')

  scope :between_dates, lambda{ |start_date, end_date|
    start_date ||= Survey.order('entered_at ASC').first.entered_at
    end_date ||= Survey.order('entered_at DESC').first.entered_at

    where(:entered_at => (start_date..end_date))
  }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  http_basic_authenticate_with(:name => "tfc-reports", :password => "functional-tfc-2012")

  def index
    if params[:from]
      from_date = Date.strptime(params[:from], '%m/%d/%Y').beginning_of_day
    else
      from_date = Survey.order('surveys.entered_at ASC').first.entered_at.beginning_of_day
    end

    if params[:to]
      to_date = Date.strptime(params[:to], '%m/%d/%Y').end_of_day
    else
      to_date = Survey.order('surveys.entered_at DESC').first.entered_at.end_of_day
    end

    @records = Survey.between_dates(from_date, to_date).order_by_date_entered

    @records = @records.with_keywords(params[:q].to_s.strip) if params[:q].present?

    respond_to do |format|
      format.xls { send_xls }
      format.html do
        @histogram_data = []

        histo_date = from_date.change(:min => from_date.min.round(-1))
        grouped_data = @records.group_by { |record|
          min = record.entered_at.min
          min_group = min - min % 10
          record.entered_at.change(:min => min_group)
        }
        while (histo_date < to_date)
          pushed = false

          grouped_data.each do |gd, records|
            if gd == histo_date
              @histogram_data << [histo_date, records.count]
              pushed = true
              break
            end
          end

          @histogram_data << [histo_date, 0] unless pushed

          histo_date += 10.minutes
        end
      end
    end

    params[:from] = from_date.strftime('%m/%d/%Y')
    params[:to] = to_date.strftime('%m/%d/%Y')
  end

  def summary
    if params[:from]
      from_date = Date.strptime(params[:from], '%m/%d/%Y').beginning_of_day
    else
      from_date = Survey.order('surveys.entered_at ASC').first.entered_at.beginning_of_day
    end

    if params[:to]
      to_date = Date.strptime(params[:to], '%m/%d/%Y').end_of_day
    else
      to_date = Survey.order('surveys.entered_at DESC').first.entered_at.end_of_day
    end

    @summaries = Survey.daily_summaries(from_date, to_date)

    params[:from] = from_date.strftime('%m/%d/%Y')
    params[:to] = to_date.strftime('%m/%d/%Y')
  end

  protected

  def send_xls
    generate_xls_from(@records,
                      "survey-#{Time.now.utc.to_i.to_s}.xls", 'Survey Data',
                      ['ID', 'Date', 'Time', 'First Name', 'Last Name', 'Email', 'Phone #', 'Postal Code', 'TFC Opt-in?', 'Rogers Opt-in?']) do |s|
      [
        s.id, s.day_entered, s.time_entered, s.first_name, s.last_name,
        s.email, s.phone_number, s.postal_code,
        s.tfc_opt_in ? 'Y' : 'N', s.rogers_opt_in ? 'Y' : 'N'
      ]
    end
  end

  def generate_xls_from(recs, file_name, sheet_name, headers, &block)
    book = Spreadsheet::Workbook.new
    sheet1 = book.create_worksheet
    sheet1.name = sheet_name

    sheet1.row(0).replace headers
    sheet1.row(0).height = 20

    i = 1
    recs.order("").find_each(:batch_size => 100) do |rec|
      sheet1.row(i).replace block.call(rec)
      i += 1
    end

    format = Spreadsheet::Format.new :color => :blue,
                                     :weight => :bold,
                                     :size => 18
    sheet1.row(0).default_format = format

    book.write "xls/#{file_name}"
    send_file "xls/#{file_name}" #, :disposition => "attachment", :stream => true, :buffer_size => 4096
  end


end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_filter :create_log_request

  def new
    @survey = Survey.new
    @survey.tfc_opt_in = true
    @survey.rogers_opt_in = true
  end

  def create
    params[:surveys].each do |survey|
      puts survey.inspect
      #Hack, get the second element in each survey array
      if Survey.where(:key => survey[1][:key]).count == 0
        s = Survey.new survey[1]
        s.save
      else
        logger.warn("Duplicate Key: #{survey.inspect}")
      end
    end

    render :nothing => true
  end

  protected

  def create_log_request
    rl = RequestLog.new :controller => params[:controller], :action => params[:action], :params => params.to_s
    rl.save
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html <%= "manifest='/survey_cache.manifest'" if controller.controller_name == 'surveys' && !Rails.env.development? %>>
<head>
  <title>Tfc</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <%= yield :head %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/reports/_topbar.html.erb
<div class="navbar">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to 'TFC', summary_reports_path, :class=>'brand' %>

      <div class="container nav-collapse">
        <ul class="nav">
          <li class="<%= 'active' if controller.action_name == 'summary' %>">
            <%= link_to 'Summaries', summary_reports_path %>
          </li>
          <li class="<%= 'active' if controller.action_name == 'index' %>">
            <%= link_to 'Entries', reports_path %>
          </li>

        </ul>
      </div>
      <!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/reports/index.html.erb
<%= render :partial => 'topbar' %>

<div class="container">
  <div class="row">
    <%= form_tag reports_path, :method => :get, :class => 'form-inlne' do%>
      <input type="text" id="report_from" name="from" value="<%= params[:from]%>" placeholder="From" class="span2"/>
      <input type="text" id="report_to" name="to" value="<%= params[:to]%>" placeholder="To" class="span2"/>
      <input type="text" id="keyword" name="q" value="<%= params[:q]%>" placeholder="Keyword" class="span2"/>
      <input type="submit" value="Generate Report" class="btn btn-large btn-warning" style="margin:0 0 9px 20px;" />
    <% end %>

    <div id="chart" class="span12" style="height:200px;width:100%;margin-bottom: 50px; margin-left:0px;"></div>



    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Time</th>
          <th>First Name</th>
          <th>Last Name</th>
          <th>Email</th>
          <th>Phone #</th>
          <th>Postal Code</th>
          <th>TFC Opt-in?</th>
          <th>Rogers Opt-in?</th>
        </tr>
      </thead>
      <tbody>
        <% @records.each do |record| %>
          <tr>
            <td><%= record.day_entered %>  </td>
            <td><%= record.time_entered %>  </td>
            <td><%= record.first_name %>  </td>
            <td><%= record.last_name %>  </td>
            <td><%= record.email %>  </td>
            <td><%= record.phone_number %>  </td>
            <td><%= record.postal_code %>  </td>
            <td><%= record.tfc_opt_in ? 'Y' : 'N' %>  </td>
            <td><%= record.rogers_opt_in ? 'Y' : 'N' %>  </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Download as XLS', params.merge(:format => :xls), :class => 'btn btn-mini' %>
    <br/><br/>

  </div>
</div>

<script>
  yAxisName = '# Entrees';
  xAxisName = 'Date';
  chartType = 'column';

  chartData = [];
<% @histogram_data.each do |point| %>
    chartData.push(
    [
      1000*parseFloat(<%= point[0].to_f %>),
      parseInt(<%= point[1] %>, 10)
    ]
  );
<% end %>
</script>

app/views/reports/summary.html.erb
<%= render :partial => 'topbar' %>

<div class="container">
  <div class="row">
    <%= form_tag summary_reports_path, :method => :get, :class => 'form-inlne' do%>
      <input type="text" id="report_from" name="from" value="<%= params[:from]%>" placeholder="From" class="span2"/>
      <input type="text" id="report_to" name="to" value="<%= params[:to]%>" placeholder="To" class="span2"/>
      <input type="submit" value="Generate Report" class="btn btn-large btn-warning" style="margin-bottom:9px;" />
    <% end %>

    <div id="chart" class="span12" style="height:200px;width:100%;margin-bottom: 50px; margin-left:0px;"></div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Date</th>
          <th>Start Time</th>
          <th>End Time</th>
          <th># Entrees</th>
          <th>% TFC Opt-in</th>
          <th>% Rogers Opt-in</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <% @summaries.each do |summary| %>
          <tr>
            <% entered_date = Date.parse(summary.entered_date) %>
            <td><%= entered_date.strftime('%b %e, %Y') %></td>
            <td><%= Time.parse(summary.start_time).strftime('%l:%H%P') %></td>
            <td><%= Time.parse(summary.end_time).strftime('%l:%H%P') %></td>
            <td><%= summary.num_of_entrees %></td>
            <td><%= "#{100 * summary.num_of_tfc_opt_ins.to_i /  summary.num_of_entrees.to_i}%" if summary.num_of_entrees.to_i > 0 %></td>
            <td><%= "#{100 * summary.num_of_rogers_opt_ins.to_i /  summary.num_of_entrees.to_i}%" if summary.num_of_entrees.to_i > 0 %></td>
            <td><%= link_to 'View', reports_path(:from => entered_date.strftime('%m/%d/%Y'), :to => entered_date.strftime('%m/%d/%Y')) %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<script>
  yAxisName = '# Entrees';
  xAxisName = 'Date';
  chartType = 'column';
  
  chartData = [];
<% @summaries.each do |summary| %>
    chartData.push(
    [
      1000*parseFloat(<%= Time.parse(summary.entered_date).to_f %>),
      parseInt(<%= summary.num_of_entrees %>, 10)
    ]
  );
<% end %>
</script>

app/views/shared/_form_errors.html.erb
<% unless f.object.errors.blank? %>
    <div class="alert alert-block alert-error">
      <strong>Hmmm, correct the following issues and try again ...</strong>
      <ul>
        <% f.object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
<% end %>